DROP TABLE IF EXISTS TRANSLATIONS;
CREATE TABLE TRANSLATIONS (
	ID INTEGER PRIMARY KEY,
	WORD_DE TEXT NOT NULL,
	ARTICLE_DE TEXT,
	OTHER_DE TEXT,
	WORD_NO TEXT NOT NULL,
	ARTICLE_NO TEXT,
	OTHER_NO TEXT
);

